version: '3.9'

services:
  users_app:
    build: ./
    command: ./users_app
    #command: ./wait-for-postgres.sh db ./users_app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=usersappdb

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=usersappdb
      - POSTGRES_PASSWORD=usersappdb
      - POSTGRES_DB=usersappdb
    ports:
      - 5436:5432