version: '3.9'

services:
  users_app:
    build: ./
    command: ./users_app
    #command: ./wait-for-postgres.sh db ./users_app
    ports:
      - 8001:8001
    depends_on:
      - db
    links:
      - db
    entrypoint: bash -c "
      until ((echo > /dev/tcp/db/5432) >/dev/null 2>&1); do sleep 5; done &&
        ./users_app"
    privileged: true

  db:
    restart: always
    image: postgres:latest
#    volumes:
 #     - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=usersappdb
      - POSTGRES_PASSWORD=usersappdb1
      - POSTGRES_DB=usersappdb
    ports:
      - 5436:5432